version: "3.8"

services:
  undefined:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: undefined
    entrypoint: sh ./.docker/entrypoint.sh
    ports:
      - 3010:3010
    volumes:
      - ./:/usr/undefined/app
    networks:
      - undefined
    environment:
      APP_VERSION: 1.0
      APP_NAME: "Undefined: Begin tests in Monolith"
      APP_PORT: 3010

networks:
  undefined:
    driver: bridge
